package src.resources;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

// End SALSA compiler generated import delcarations.


public class Status extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getReception().getLocation() + System.getProperty("identifier"));
		}
		Status instance = (Status)new Status(uan, ual).construct();
		{
			Object[] _arguments = { args };
			instance.send( new Message(instance, instance, "act", _arguments, null, null) );
		}
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Status(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Status.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Status(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Status.getReferenceByLocation(new UAL(ual)); }
	public Status(boolean o, UAN __uan)	{ super(o,__uan); }
	public Status(boolean o, UAL __ual)	{ super(o,__ual); }

	public Status(UAN __uan)	{ this(__uan, null); }
	public Status(UAL __ual)	{ this(null, __ual); }
	public Status()		{ this(null, null);  }
	public Status(UAN __uan, UAL __ual) {
		if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getReception().getLocation())) {
			createRemotely(__uan, __ual, "src.resources.Status");
		} else {
			State state = new State(__uan, __ual);
			state.updateSelf(this);
			ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor.State {
		public Status self;
		public Status.State  _this = this;
		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "src.resources.Status$State" );
			addMethodsForClasses();
		}

		public void updateSelf(ActorReference actorReference) {
			self = (Status)actorReference;
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			super.updateSelf(self);
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Throwable exception = null;

			if (matches != null) {
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			String exceptionMessage = "Message processing exception:\n";
			if (message.getSource() != null) {
				exceptionMessage += "\tSent by: " + message.getSource().toString() + "\n";
			} else exceptionMessage += "\tSent by: unknown\n";
			exceptionMessage += "\tReceived by actor: " + toString() + "\n";
			exceptionMessage += "\tMessage: " + message.toString() + "\n";
			if (exception == null) {
				if (matches == null) {
					exceptionMessage += "\tNo methods with the same name found.\n";
				System.err.println(exceptionMessage);
					return;
				}
				exceptionMessage += "\tDid not match any of the following: \n";
				for (int i = 0; i < matches.length; i++) {
					exceptionMessage += "\t\tMethod: " + matches[i].getName() + "( ";
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						exceptionMessage += parTypes[j].getName() + " ";
					}
					exceptionMessage += ")\n";
				}
				System.err.println(exceptionMessage);
				return;
			} else {
				exceptionMessage += "\tThrew exception: " + exception + "\n";
				System.err.println(exceptionMessage);
				exception.printStackTrace();
			}
		}

		public void act(String[] arguments) {
			if (arguments.length==0) {
				System.err.println("Usage: java io.resources.Status <ProtocolActor UAL or PeerServer UAL>*");
			}
			{
				Token token_2_0 = new Token();
				// join block
				token_2_0.setJoinDirector();
				for (int i = 0; i<arguments.length; i++){
					UAL ual = new UAL(arguments[i]);
					if (ual.getIdentifier().equals("/io/peerServer")) {
						{
							Token token_5_0 = new Token();
							// new UniversalActor(ual)<-statusAll()
							{
								Object _arguments[] = {  };
								Message __message = new Message( self, new UniversalActor(ual), "statusAll", _arguments, null, token_5_0 );
								__messages.add( __message );
							}
							// standardOutput<-println(token)
							{
								Object _arguments[] = { token_5_0 };
								Message __message = new Message( self, standardOutput, "println", _arguments, token_5_0, token_2_0 );
								__messages.add( __message );
							}
						}
					}
					else if (ual.getIdentifier().equals("/io/protocolActor")) {
						{
							Token token_5_0 = new Token();
							// new UniversalActor(ual)<-status()
							{
								Object _arguments[] = {  };
								Message __message = new Message( self, new UniversalActor(ual), "status", _arguments, null, token_5_0 );
								__messages.add( __message );
							}
							// standardOutput<-println(token)
							{
								Object _arguments[] = { token_5_0 };
								Message __message = new Message( self, standardOutput, "println", _arguments, token_5_0, token_2_0 );
								__messages.add( __message );
							}
						}
					}
					else {
						{
							// standardOutput<-println("Invalid ual: "+ual.toString())
							{
								Object _arguments[] = { "Invalid ual: "+ual.toString() };
								Message __message = new Message( self, standardOutput, "println", _arguments, null, token_2_0 );
								__messages.add( __message );
							}
						}
					}
				}
				token_2_0.createJoinDirector();
				// completed()
				{
					Object _arguments[] = {  };
					Message __message = new Message( self, self, "completed", _arguments, token_2_0, null );
					__messages.add( __message );
				}
			}
		}
		public void completed() {
			System.exit(0);
		}
	}
}